# Generated by Django 2.2 on 2019-04-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='imgs/dummy.jpg', height_field='image_height', upload_to='imgs/', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='card',
            name='image_height',
            field=models.PositiveIntegerField(default='528'),
        ),
        migrations.AddField(
            model_name='card',
            name='image_width',
            field=models.PositiveIntegerField(default='360'),
        ),
    ]
